name: Django tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

# on:
#   schedule:
#     - cron: "0 3 * * 1,3,5" # Runs at 03:00 AM (UTC) every Monday, Wednesday, and Friday (Check https://crontab.guru/)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.9
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8 
          flake8
      - name: Coverage report
        run: |
          pip install coverage 
          coverage run manage.py test
          coverage report
          coverage html
      - name: Django Testing
        run: |
          python manage.py test
